-- V3: Production-ready PostgreSQL schema for the music platform.
-- This script is intended for a fresh database bootstrap.
-- If you already have V1/V2 applied, do NOT run this on the same database without a controlled migration plan.

BEGIN;

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    display_name VARCHAR(120),
    avatar_url VARCHAR(512),
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    registration_date TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_login_at TIMESTAMPTZ,
    email_verified_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_status CHECK (status IN ('ACTIVE', 'DISABLED', 'PENDING', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_users_username ON users (username);
CREATE INDEX IF NOT EXISTS idx_users_email ON users (email);
CREATE INDEX IF NOT EXISTS idx_users_status ON users (status);

CREATE TABLE IF NOT EXISTS roles (
    role_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(64) NOT NULL,
    name VARCHAR(100) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_roles_code UNIQUE (code),
    CONSTRAINT uk_roles_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id UUID NOT NULL,
    role_id SMALLINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_roles_role_id ON user_roles (role_id);

CREATE TABLE IF NOT EXISTS artists (
    artist_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    bio TEXT,
    image_url VARCHAR(512),
    banner_url VARCHAR(512),
    country VARCHAR(100),
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_artists_slug UNIQUE (slug),
    CONSTRAINT ck_artists_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_artists_slug ON artists (slug);
CREATE INDEX IF NOT EXISTS idx_artists_name ON artists (name);
CREATE INDEX IF NOT EXISTS idx_artists_verified ON artists (verified);

CREATE TABLE IF NOT EXISTS albums (
    album_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    description TEXT,
    release_date DATE,
    cover_url VARCHAR(512),
    album_type VARCHAR(32) NOT NULL DEFAULT 'ALBUM',
    primary_artist_id UUID,
    status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_albums_slug UNIQUE (slug),
    CONSTRAINT fk_albums_primary_artist
        FOREIGN KEY (primary_artist_id)
        REFERENCES artists (artist_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_albums_type CHECK (album_type IN ('SINGLE', 'EP', 'ALBUM', 'COMPILATION')),
    CONSTRAINT ck_albums_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_albums_primary_artist_id ON albums (primary_artist_id);
CREATE INDEX IF NOT EXISTS idx_albums_release_date ON albums (release_date DESC);
CREATE INDEX IF NOT EXISTS idx_albums_type ON albums (album_type);

CREATE TABLE IF NOT EXISTS genres (
    genre_id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(120) NOT NULL,
    slug VARCHAR(160) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_genres_name UNIQUE (name),
    CONSTRAINT uk_genres_slug UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS songs (
    song_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    duration_seconds INTEGER NOT NULL,
    release_date DATE,
    audio_url VARCHAR(512) NOT NULL,
    cover_url VARCHAR(512),
    lyrics TEXT,
    explicit BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'PUBLISHED',
    album_id UUID,
    track_number INTEGER,
    disc_number INTEGER,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_songs_slug UNIQUE (slug),
    CONSTRAINT fk_songs_album
        FOREIGN KEY (album_id)
        REFERENCES albums (album_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_songs_duration_positive CHECK (duration_seconds > 0),
    CONSTRAINT ck_songs_status CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED'))
);

CREATE INDEX IF NOT EXISTS idx_songs_slug ON songs (slug);
CREATE INDEX IF NOT EXISTS idx_songs_title ON songs (title);
CREATE INDEX IF NOT EXISTS idx_songs_album_id ON songs (album_id);
CREATE INDEX IF NOT EXISTS idx_songs_release_date ON songs (release_date DESC);
CREATE INDEX IF NOT EXISTS idx_songs_status ON songs (status);
CREATE INDEX IF NOT EXISTS idx_songs_explicit ON songs (explicit);

CREATE TABLE IF NOT EXISTS song_artists (
    song_id UUID NOT NULL,
    artist_id UUID NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'MAIN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (song_id, artist_id, role),
    CONSTRAINT fk_song_artists_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_song_artists_artist
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_song_artists_role CHECK (role IN ('MAIN', 'FEATURED', 'PRODUCER', 'COMPOSER', 'LYRICIST'))
);

CREATE INDEX IF NOT EXISTS idx_song_artists_song_id ON song_artists (song_id);
CREATE INDEX IF NOT EXISTS idx_song_artists_artist_id ON song_artists (artist_id);

CREATE TABLE IF NOT EXISTS song_genres (
    song_id UUID NOT NULL,
    genre_id SMALLINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (song_id, genre_id),
    CONSTRAINT fk_song_genres_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_song_genres_genre
        FOREIGN KEY (genre_id)
        REFERENCES genres (genre_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_song_genres_song_id ON song_genres (song_id);
CREATE INDEX IF NOT EXISTS idx_song_genres_genre_id ON song_genres (genre_id);

CREATE TABLE IF NOT EXISTS playlists (
    playlist_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL,
    name VARCHAR(255) NOT NULL,
    slug VARCHAR(200) NOT NULL,
    description TEXT,
    cover_url VARCHAR(512),
    visibility VARCHAR(32) NOT NULL DEFAULT 'PRIVATE',
    collaborative BOOLEAN NOT NULL DEFAULT FALSE,
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_playlists_slug UNIQUE (slug),
    CONSTRAINT fk_playlists_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_playlists_visibility CHECK (visibility IN ('PRIVATE', 'UNLISTED', 'PUBLIC')),
    CONSTRAINT ck_playlists_status CHECK (status IN ('ACTIVE', 'ARCHIVED', 'DELETED'))
);

CREATE INDEX IF NOT EXISTS idx_playlists_user_id_created_at ON playlists (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_playlists_slug ON playlists (slug);
CREATE INDEX IF NOT EXISTS idx_playlists_visibility ON playlists (visibility);

CREATE TABLE IF NOT EXISTS playlist_tracks (
    playlist_id UUID NOT NULL,
    song_id UUID NOT NULL,
    position INTEGER NOT NULL,
    added_by_user_id UUID,
    added_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (playlist_id, position),
    CONSTRAINT uk_playlist_tracks_playlist_song UNIQUE (playlist_id, song_id),
    CONSTRAINT fk_playlist_tracks_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlists (playlist_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_playlist_tracks_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_playlist_tracks_added_by_user
        FOREIGN KEY (added_by_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_playlist_tracks_playlist_id ON playlist_tracks (playlist_id);
CREATE INDEX IF NOT EXISTS idx_playlist_tracks_song_id ON playlist_tracks (song_id);
CREATE INDEX IF NOT EXISTS idx_playlist_tracks_added_by_user_id ON playlist_tracks (added_by_user_id);
CREATE INDEX IF NOT EXISTS idx_playlist_tracks_position ON playlist_tracks (playlist_id, position);

CREATE TABLE IF NOT EXISTS user_liked_songs (
    user_id UUID NOT NULL,
    song_id UUID NOT NULL,
    liked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, song_id),
    CONSTRAINT fk_user_liked_songs_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_liked_songs_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_liked_songs_song_id ON user_liked_songs (song_id);
CREATE INDEX IF NOT EXISTS idx_user_liked_songs_liked_at ON user_liked_songs (liked_at DESC);

CREATE TABLE IF NOT EXISTS user_followed_artists (
    user_id UUID NOT NULL,
    artist_id UUID NOT NULL,
    followed_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, artist_id),
    CONSTRAINT fk_user_followed_artists_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_user_followed_artists_artist
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_user_followed_artists_artist_id ON user_followed_artists (artist_id);
CREATE INDEX IF NOT EXISTS idx_user_followed_artists_followed_at ON user_followed_artists (followed_at DESC);

CREATE TABLE IF NOT EXISTS play_history (
    play_history_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    song_id UUID NOT NULL,
    played_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    played_seconds INTEGER NOT NULL DEFAULT 0,
    source VARCHAR(32) NOT NULL DEFAULT 'DIRECT',
    device_type VARCHAR(32),
    session_id VARCHAR(128),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_play_history_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT fk_play_history_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_play_history_played_seconds CHECK (played_seconds >= 0),
    CONSTRAINT ck_play_history_source CHECK (source IN ('DIRECT', 'SEARCH', 'PLAYLIST', 'HOME', 'RECOMMENDATION'))
);

CREATE INDEX IF NOT EXISTS idx_play_history_user_id_played_at ON play_history (user_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_play_history_song_id_played_at ON play_history (song_id, played_at DESC);
CREATE INDEX IF NOT EXISTS idx_play_history_played_at ON play_history (played_at DESC);

CREATE TABLE IF NOT EXISTS refresh_tokens (
    refresh_token_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    token_hash VARCHAR(255) NOT NULL,
    issued_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMPTZ NOT NULL,
    revoked_at TIMESTAMPTZ,
    device_name VARCHAR(120),
    ip_address VARCHAR(64),
    user_agent TEXT,
    CONSTRAINT uk_refresh_tokens_token_hash UNIQUE (token_hash),
    CONSTRAINT fk_refresh_tokens_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_refresh_tokens_user_id ON refresh_tokens (user_id);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_expires_at ON refresh_tokens (expires_at);
CREATE INDEX IF NOT EXISTS idx_refresh_tokens_revoked_at ON refresh_tokens (revoked_at);

CREATE TABLE IF NOT EXISTS audit_logs (
    audit_log_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID,
    action VARCHAR(80) NOT NULL,
    entity_type VARCHAR(80) NOT NULL,
    entity_id VARCHAR(80),
    metadata JSONB,
    ip_address VARCHAR(64),
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_audit_logs_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user_id_created_at ON audit_logs (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity_type_entity_id ON audit_logs (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_audit_logs_created_at ON audit_logs (created_at DESC);

COMMIT;
