-- ========================================
-- PostgreSQL schema for Music Streaming App
-- ========================================
-- Chạy file này để tạo các bảng cần thiết trước khi seed dữ liệu.

DROP TABLE IF EXISTS playlist_songs CASCADE;
DROP TABLE IF EXISTS playlists CASCADE;
DROP TABLE IF EXISTS songs CASCADE;
DROP TABLE IF EXISTS artists CASCADE;
DROP TABLE IF EXISTS users CASCADE;

-- ========================================
-- ARTISTS
-- ========================================
CREATE TABLE artists (
    artist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    bio TEXT,
    image_url VARCHAR(512),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- ========================================
-- USERS
-- ========================================
CREATE TABLE users (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    registration_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_username UNIQUE (username),
    CONSTRAINT uk_users_email UNIQUE (email)
);

-- ========================================
-- SONGS
-- ========================================
CREATE TABLE songs (
    song_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    duration INTEGER,
    release_date DATE,
    audio_url VARCHAR(512),
    image_url VARCHAR(512),
    artist_id BIGINT,
    CONSTRAINT fk_songs_artist
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE SET NULL
);

CREATE INDEX idx_songs_title ON songs (title);
CREATE INDEX idx_songs_artist_id ON songs (artist_id);

-- ========================================
-- PLAYLISTS
-- ========================================
CREATE TABLE playlists (
    playlist_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_playlists_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE INDEX idx_playlists_user_id ON playlists (user_id);

-- ========================================
-- PLAYLIST_SONGS
-- ========================================
CREATE TABLE playlist_songs (
    playlist_song_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    playlist_id BIGINT NOT NULL,
    song_id BIGINT NOT NULL,
    song_order INTEGER,
    CONSTRAINT fk_playlist_songs_playlist
        FOREIGN KEY (playlist_id)
        REFERENCES playlists (playlist_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_playlist_songs_song
        FOREIGN KEY (song_id)
        REFERENCES songs (song_id)
        ON DELETE CASCADE,
    CONSTRAINT uk_playlist_song UNIQUE (playlist_id, song_id)
);

CREATE INDEX idx_playlist_songs_playlist_id ON playlist_songs (playlist_id);
CREATE INDEX idx_playlist_songs_song_id ON playlist_songs (song_id);
