-- V5: Add community identity, profile, permissions, and artist ownership foundations.

BEGIN;

CREATE TABLE IF NOT EXISTS user_profiles (
    user_id UUID PRIMARY KEY,
    handle VARCHAR(80) NOT NULL,
    display_name VARCHAR(120) NOT NULL,
    bio TEXT,
    avatar_url VARCHAR(512),
    banner_url VARCHAR(512),
    website_url VARCHAR(512),
    location VARCHAR(120),
    visibility VARCHAR(32) NOT NULL DEFAULT 'PUBLIC',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_user_profiles_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT uk_user_profiles_handle UNIQUE (handle),
    CONSTRAINT ck_user_profiles_visibility CHECK (visibility IN ('PUBLIC', 'PRIVATE'))
);

INSERT INTO user_profiles (user_id, handle, display_name, avatar_url, created_at, updated_at)
SELECT
    user_id,
    username,
    COALESCE(display_name, username),
    avatar_url,
    CURRENT_TIMESTAMP,
    CURRENT_TIMESTAMP
FROM users
ON CONFLICT (user_id) DO NOTHING;

CREATE TABLE IF NOT EXISTS permissions (
    permission_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code VARCHAR(100) NOT NULL,
    name VARCHAR(120) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_permissions_code UNIQUE (code),
    CONSTRAINT uk_permissions_name UNIQUE (name)
);

CREATE TABLE IF NOT EXISTS role_permissions (
    role_id BIGINT NOT NULL,
    permission_id BIGINT NOT NULL,
    assigned_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_role
        FOREIGN KEY (role_id)
        REFERENCES roles (role_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_permission
        FOREIGN KEY (permission_id)
        REFERENCES permissions (permission_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS artist_members (
    artist_id UUID NOT NULL,
    user_id UUID NOT NULL,
    role VARCHAR(32) NOT NULL DEFAULT 'OWNER',
    status VARCHAR(32) NOT NULL DEFAULT 'ACTIVE',
    joined_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    invited_by_user_id UUID,
    PRIMARY KEY (artist_id, user_id),
    CONSTRAINT fk_artist_members_artist
        FOREIGN KEY (artist_id)
        REFERENCES artists (artist_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artist_members_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_artist_members_invited_by_user
        FOREIGN KEY (invited_by_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_artist_members_role CHECK (role IN ('OWNER', 'MANAGER', 'EDITOR')),
    CONSTRAINT ck_artist_members_status CHECK (status IN ('ACTIVE', 'REMOVED'))
);

INSERT INTO roles (code, name)
VALUES
    ('USER', 'User'),
    ('ARTIST', 'Artist'),
    ('MODERATOR', 'Moderator'),
    ('ADMIN', 'Administrator')
ON CONFLICT (code) DO NOTHING;

INSERT INTO permissions (code, name, description)
VALUES
    ('song:read', 'Read songs', 'View published songs.'),
    ('song:create', 'Create songs', 'Create song drafts or submissions.'),
    ('song:publish', 'Publish songs', 'Publish approved songs.'),
    ('playlist:create', 'Create playlists', 'Create personal playlists.'),
    ('playlist:collaborate', 'Collaborate on playlists', 'Edit playlists shared by another user.'),
    ('comment:create', 'Create comments', 'Comment on community content.'),
    ('moderation:review', 'Review moderation queue', 'Review reports and pending content.'),
    ('admin:manage', 'Manage platform', 'Manage platform-wide settings and users.')
ON CONFLICT (code) DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN ('song:read', 'playlist:create', 'comment:create')
WHERE r.code = 'USER'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN ('song:read', 'song:create', 'playlist:create', 'playlist:collaborate', 'comment:create')
WHERE r.code = 'ARTIST'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN ('song:read', 'playlist:create', 'comment:create', 'moderation:review')
WHERE r.code = 'MODERATOR'
ON CONFLICT DO NOTHING;

INSERT INTO role_permissions (role_id, permission_id)
SELECT r.role_id, p.permission_id
FROM roles r
JOIN permissions p ON p.code IN (
    'song:read',
    'song:create',
    'song:publish',
    'playlist:create',
    'playlist:collaborate',
    'comment:create',
    'moderation:review',
    'admin:manage'
)
WHERE r.code = 'ADMIN'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id
FROM users u
JOIN roles r ON r.code = 'USER'
ON CONFLICT DO NOTHING;

INSERT INTO user_roles (user_id, role_id)
SELECT u.user_id, r.role_id
FROM users u
JOIN roles r ON r.code = 'ADMIN'
WHERE u.username = 'admin'
ON CONFLICT DO NOTHING;

CREATE INDEX IF NOT EXISTS idx_user_profiles_handle ON user_profiles (handle);
CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id ON role_permissions (permission_id);
CREATE INDEX IF NOT EXISTS idx_artist_members_user_id ON artist_members (user_id);
CREATE INDEX IF NOT EXISTS idx_artist_members_status ON artist_members (status);

COMMIT;
