-- V7: Add moderation state, reports, and moderation action history.

BEGIN;

ALTER TABLE users ADD COLUMN IF NOT EXISTS suspended_until TIMESTAMPTZ;
ALTER TABLE users ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE users DROP CONSTRAINT IF EXISTS ck_users_status;
ALTER TABLE users
    ADD CONSTRAINT ck_users_status
    CHECK (status IN ('ACTIVE', 'DISABLED', 'PENDING', 'SUSPENDED', 'DELETED'));

ALTER TABLE songs ADD COLUMN IF NOT EXISTS submitted_by_user_id UUID;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE songs ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
ALTER TABLE songs ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE albums ADD COLUMN IF NOT EXISTS submitted_by_user_id UUID;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE albums ADD COLUMN IF NOT EXISTS published_at TIMESTAMPTZ;
ALTER TABLE albums ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE artists ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE artists ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE playlists ADD COLUMN IF NOT EXISTS moderation_status VARCHAR(32) NOT NULL DEFAULT 'APPROVED';
ALTER TABLE playlists ADD COLUMN IF NOT EXISTS deleted_at TIMESTAMPTZ;

ALTER TABLE songs DROP CONSTRAINT IF EXISTS ck_songs_status;
ALTER TABLE songs
    ADD CONSTRAINT ck_songs_status
    CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED', 'TAKEN_DOWN', 'DELETED'));

ALTER TABLE albums DROP CONSTRAINT IF EXISTS ck_albums_status;
ALTER TABLE albums
    ADD CONSTRAINT ck_albums_status
    CHECK (status IN ('DRAFT', 'PUBLISHED', 'ARCHIVED', 'TAKEN_DOWN', 'DELETED'));

ALTER TABLE artists DROP CONSTRAINT IF EXISTS ck_artists_status;
ALTER TABLE artists
    ADD CONSTRAINT ck_artists_status
    CHECK (status IN ('ACTIVE', 'INACTIVE', 'ARCHIVED', 'SUSPENDED', 'DELETED'));

ALTER TABLE playlists DROP CONSTRAINT IF EXISTS ck_playlists_status;
ALTER TABLE playlists
    ADD CONSTRAINT ck_playlists_status
    CHECK (status IN ('ACTIVE', 'ARCHIVED', 'TAKEN_DOWN', 'DELETED'));

DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_songs_submitted_by_user') THEN
        ALTER TABLE songs
            ADD CONSTRAINT fk_songs_submitted_by_user
            FOREIGN KEY (submitted_by_user_id)
            REFERENCES users (user_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'fk_albums_submitted_by_user') THEN
        ALTER TABLE albums
            ADD CONSTRAINT fk_albums_submitted_by_user
            FOREIGN KEY (submitted_by_user_id)
            REFERENCES users (user_id)
            ON DELETE SET NULL;
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_songs_moderation_status') THEN
        ALTER TABLE songs
            ADD CONSTRAINT ck_songs_moderation_status
            CHECK (moderation_status IN ('PENDING', 'APPROVED', 'REJECTED', 'TAKEN_DOWN'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_albums_moderation_status') THEN
        ALTER TABLE albums
            ADD CONSTRAINT ck_albums_moderation_status
            CHECK (moderation_status IN ('PENDING', 'APPROVED', 'REJECTED', 'TAKEN_DOWN'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_artists_moderation_status') THEN
        ALTER TABLE artists
            ADD CONSTRAINT ck_artists_moderation_status
            CHECK (moderation_status IN ('PENDING', 'APPROVED', 'REJECTED', 'TAKEN_DOWN'));
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'ck_playlists_moderation_status') THEN
        ALTER TABLE playlists
            ADD CONSTRAINT ck_playlists_moderation_status
            CHECK (moderation_status IN ('PENDING', 'APPROVED', 'REJECTED', 'TAKEN_DOWN'));
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS reports (
    report_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    reporter_user_id UUID NOT NULL,
    entity_type VARCHAR(32) NOT NULL,
    entity_id VARCHAR(80) NOT NULL,
    reason VARCHAR(64) NOT NULL,
    description TEXT,
    status VARCHAR(32) NOT NULL DEFAULT 'PENDING',
    reviewed_by_user_id UUID,
    reviewed_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_reports_reporter_user
        FOREIGN KEY (reporter_user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_reports_reviewed_by_user
        FOREIGN KEY (reviewed_by_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_reports_entity_type CHECK (entity_type IN ('USER', 'ARTIST', 'ALBUM', 'SONG', 'PLAYLIST', 'COMMENT')),
    CONSTRAINT ck_reports_reason CHECK (reason IN ('SPAM', 'HARASSMENT', 'COPYRIGHT', 'EXPLICIT', 'MISINFORMATION', 'OTHER')),
    CONSTRAINT ck_reports_status CHECK (status IN ('PENDING', 'REVIEWING', 'DISMISSED', 'ACTIONED'))
);

CREATE TABLE IF NOT EXISTS moderation_actions (
    moderation_action_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    moderator_user_id UUID,
    target_type VARCHAR(32) NOT NULL,
    target_id VARCHAR(80) NOT NULL,
    action VARCHAR(64) NOT NULL,
    reason TEXT,
    metadata JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_moderation_actions_moderator_user
        FOREIGN KEY (moderator_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_moderation_actions_target_type CHECK (target_type IN ('USER', 'ARTIST', 'ALBUM', 'SONG', 'PLAYLIST', 'COMMENT')),
    CONSTRAINT ck_moderation_actions_action CHECK (action IN ('WARN', 'APPROVE', 'REJECT', 'HIDE', 'RESTORE', 'TAKE_DOWN', 'SUSPEND_USER', 'DELETE'))
);

CREATE INDEX IF NOT EXISTS idx_users_status_suspended_until ON users (status, suspended_until);
CREATE INDEX IF NOT EXISTS idx_users_deleted_at ON users (deleted_at);
CREATE INDEX IF NOT EXISTS idx_songs_moderation_status ON songs (moderation_status);
CREATE INDEX IF NOT EXISTS idx_songs_submitted_by_user_id ON songs (submitted_by_user_id);
CREATE INDEX IF NOT EXISTS idx_songs_deleted_at ON songs (deleted_at);
CREATE INDEX IF NOT EXISTS idx_albums_moderation_status ON albums (moderation_status);
CREATE INDEX IF NOT EXISTS idx_artists_moderation_status ON artists (moderation_status);
CREATE INDEX IF NOT EXISTS idx_playlists_moderation_status ON playlists (moderation_status);
CREATE INDEX IF NOT EXISTS idx_reports_reporter_user_id ON reports (reporter_user_id);
CREATE INDEX IF NOT EXISTS idx_reports_entity ON reports (entity_type, entity_id);
CREATE INDEX IF NOT EXISTS idx_reports_status_created_at ON reports (status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_moderation_actions_target ON moderation_actions (target_type, target_id);
CREATE INDEX IF NOT EXISTS idx_moderation_actions_moderator_user_id ON moderation_actions (moderator_user_id);
CREATE INDEX IF NOT EXISTS idx_moderation_actions_created_at ON moderation_actions (created_at DESC);

COMMIT;
