-- V8: Add community comments, comment likes, and notifications.

BEGIN;

CREATE TABLE IF NOT EXISTS comments (
    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    entity_type VARCHAR(32) NOT NULL,
    entity_id VARCHAR(80) NOT NULL,
    parent_comment_id BIGINT,
    body TEXT NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'VISIBLE',
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at TIMESTAMPTZ,
    CONSTRAINT fk_comments_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_comments_parent_comment
        FOREIGN KEY (parent_comment_id)
        REFERENCES comments (comment_id)
        ON DELETE CASCADE,
    CONSTRAINT ck_comments_entity_type CHECK (entity_type IN ('ARTIST', 'ALBUM', 'SONG', 'PLAYLIST')),
    CONSTRAINT ck_comments_status CHECK (status IN ('VISIBLE', 'HIDDEN', 'DELETED')),
    CONSTRAINT ck_comments_body_not_blank CHECK (length(btrim(body)) > 0)
);

CREATE TABLE IF NOT EXISTS comment_likes (
    comment_id BIGINT NOT NULL,
    user_id UUID NOT NULL,
    liked_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (comment_id, user_id),
    CONSTRAINT fk_comment_likes_comment
        FOREIGN KEY (comment_id)
        REFERENCES comments (comment_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_comment_likes_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS notifications (
    notification_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID NOT NULL,
    actor_user_id UUID,
    type VARCHAR(64) NOT NULL,
    entity_type VARCHAR(32),
    entity_id VARCHAR(80),
    data JSONB,
    read_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_notifications_user
        FOREIGN KEY (user_id)
        REFERENCES users (user_id)
        ON DELETE CASCADE,
    CONSTRAINT fk_notifications_actor_user
        FOREIGN KEY (actor_user_id)
        REFERENCES users (user_id)
        ON DELETE SET NULL,
    CONSTRAINT ck_notifications_type CHECK (type IN (
        'COMMENT_REPLY',
        'COMMENT_LIKE',
        'PLAYLIST_SAVE',
        'USER_FOLLOW',
        'ARTIST_FOLLOW',
        'MODERATION_UPDATE',
        'SYSTEM'
    )),
    CONSTRAINT ck_notifications_entity_type CHECK (
        entity_type IS NULL
        OR entity_type IN ('USER', 'ARTIST', 'ALBUM', 'SONG', 'PLAYLIST', 'COMMENT')
    )
);

CREATE INDEX IF NOT EXISTS idx_comments_entity_created_at ON comments (entity_type, entity_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_user_id_created_at ON comments (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_comments_parent_comment_id ON comments (parent_comment_id);
CREATE INDEX IF NOT EXISTS idx_comments_status ON comments (status);
CREATE INDEX IF NOT EXISTS idx_comment_likes_user_id ON comment_likes (user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id_created_at ON notifications (user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_notifications_user_id_read_at ON notifications (user_id, read_at);
CREATE INDEX IF NOT EXISTS idx_notifications_actor_user_id ON notifications (actor_user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_entity ON notifications (entity_type, entity_id);

COMMIT;
